backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

locale: "fr"

slug:
  encoding: "ascii"
  clean_accents: true

media_folder: "_site/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD",
          picker_utc: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["article"] }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.njk",
        }
      - { label: "Post Body", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD",
          picker_utc: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["article"] }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.njk",
        }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Post Body", name: "body", widget: "markdown" }
